"""change col attached_message_id to forwarded_from_user_id in messages table

Revision ID: 0160ada0211e
Revises: d1b50fefaa95
Create Date: 2025-05-31 16:14:17.914843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0160ada0211e'
down_revision: Union[str, None] = 'd1b50fefaa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('forwarded_from_user_id', sa.CHAR(length=36), nullable=True))
    op.drop_constraint('messages_ibfk_1', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['forwarded_from_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'attached_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attached_message_id', mysql.CHAR(length=36), nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ibfk_1', 'messages', 'messages', ['attached_message_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'forwarded_from_user_id')
    # ### end Alembic commands ###
