"""change field description to descriptions in apk_update

Revision ID: 09630a8287da
Revises: 010bd765a207
Create Date: 2025-04-29 15:42:52.796944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09630a8287da'
down_revision: Union[str, None] = '010bd765a207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('apk_updates', sa.Column('descriptions', sa.JSON(), nullable=False))

	conn = op.get_bind()
	conn.execute(
		sa.text("""
			UPDATE apk_updates
			SET descriptions = JSON_ARRAY(description)
		""")
	)

	op.drop_column('apk_updates', 'description')
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('apk_updates', sa.Column('description', mysql.VARCHAR(length=512), nullable=False))

	conn = op.get_bind()
	conn.execute(
		sa.text("""
			UPDATE apk_updates
			SET description =
				CASE
					WHEN JSON_LENGTH(descriptions) > 0
					THEN JSON_UNQUOTE(JSON_EXTRACT(descriptions, '$[0]'))
					ELSE 'no description'
				END
		""")
	)

	op.drop_column('apk_updates', 'descriptions')
	# ### end Alembic commands ###
