"""add chat and message tables

Revision ID: 11b6a357d826
Revises: f6bb9c6e1b44
Create Date: 2025-05-29 21:27:28.277782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b6a357d826'
down_revision: Union[str, None] = 'f6bb9c6e1b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('user1_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user2_id', sa.CHAR(length=36), nullable=False),
    sa.Column('last_message_id', sa.CHAR(length=36), nullable=True),
    sa.Column('last_message_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['last_message_id'], ['messages.id'], name='fk_chats_last_message_id', ondelete='SET NULL', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_chats_user_pair')
    )
    op.create_index('ix_chats_last_message_created_at', 'chats', ['last_message_created_at'], unique=False)
    op.create_index('ix_chats_user1_user2', 'chats', ['user1_id', 'user2_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('chat_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sender_id', sa.CHAR(length=36), nullable=False),
    sa.Column('recipient_id', sa.CHAR(length=36), nullable=False),
    sa.Column('text_content', sa.String(length=10000), nullable=False),
    sa.Column('attachment_type', sa.Enum('message', 'post', 'images', name='messageatype'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attached_image_keys', sa.JSON(), nullable=True),
    sa.Column('attached_message_id', sa.CHAR(length=36), nullable=True),
    sa.Column('attached_post_id', sa.CHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['attached_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attached_post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_messages_chat_id', 'messages', ['chat_id'], unique=False)
    op.create_index('ix_messages_chat_id_created_at', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_recipient_id', 'messages', ['recipient_id'], unique=False)
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_index('ix_messages_recipient_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_index('ix_messages_chat_id_created_at', table_name='messages')
    op.drop_index('ix_messages_chat_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_chats_user1_user2', table_name='chats')
    op.drop_index('ix_chats_last_message_created_at', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
