"""add fields created_at and updated_at to fcm_tokens table

Revision ID: 1e6463f1b45c
Revises: 31b027629d12
Create Date: 2025-06-11 17:50:31.120334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6463f1b45c'
down_revision: Union[str, None] = '31b027629d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fcm_tokens', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('fcm_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fcm_tokens', 'updated_at')
    op.drop_column('fcm_tokens', 'created_at')
    # ### end Alembic commands ###
