"""change image_key field to images_count in tables and avatar_key to avatar_id in users table

Revision ID: 2ee096c139cd
Revises: 3aaac5ddff92
Create Date: 2025-06-04 12:11:34.833385

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2ee096c139cd'
down_revision: Union[str, None] = '3aaac5ddff92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM messages WHERE attachment_type = 'images';"
    )
    op.add_column('messages', sa.Column('attached_images_count', sa.Integer(), nullable=True))
    op.drop_column('messages', 'attached_image_keys')

    op.execute("DELETE FROM posts;")
    op.add_column('posts', sa.Column('images_count', sa.Integer(), nullable=False))
    op.drop_column('posts', 'image_keys')

    op.execute(
        "UPDATE users SET avatar_type = NULL WHERE avatar_type = 'external';"
    )
    op.add_column('users', sa.Column('avatar_id', sa.String(length=36), nullable=True))
    op.drop_column('users', 'avatar_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_key', mysql.VARCHAR(length=41), nullable=True))
    op.drop_column('users', 'avatar_id')

    now = datetime.now(timezone.utc)
    op.execute(f"""
        UPDATE posts
        SET deleted_at = '{now}', images_count = 0
        WHERE attachment_type = 'images' AND deleted_at IS NULL;
    """)
    op.add_column('posts', sa.Column('image_keys', mysql.JSON(), nullable=False))
    op.drop_column('posts', 'images_count')

    op.execute(f"""
        UPDATE messages
        SET deleted_at = '{now}'
        WHERE deleted_at IS NULL;
    """)
    op.add_column('messages', sa.Column('attached_image_keys', mysql.JSON(), nullable=True))
    op.drop_column('messages', 'attached_images_count')
    # ### end Alembic commands ###
