"""recreate field attachemnt_type in messages table

Revision ID: 3aaac5ddff92
Revises: 59b8c6b4ca40
Create Date: 2025-06-01 04:37:03.741710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaac5ddff92'
down_revision: Union[str, None] = '59b8c6b4ca40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachment_type', sa.Enum('post', 'images', name='messageatype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachment_type')
    # ### end Alembic commands ###
