"""changed field images_count to image_exts in post model

Revision ID: 5166955b27ea
Revises: 4e60d9c5cf2a
Create Date: 2025-05-03 18:18:45.002990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5166955b27ea'
down_revision: Union[str, None] = '4e60d9c5cf2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_exts', sa.JSON(), nullable=False))
    op.drop_column('posts', 'images_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('images_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'image_exts')
    # ### end Alembic commands ###
