"""remove field attachment_type from messages table

Revision ID: 59b8c6b4ca40
Revises: 0160ada0211e
Create Date: 2025-06-01 04:35:17.077506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '59b8c6b4ca40'
down_revision: Union[str, None] = '0160ada0211e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'attachment_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('attachment_type', mysql.ENUM('message', 'post', 'images'), nullable=True))
    # ### end Alembic commands ###
