"""change primary keys in refresh_token model

Revision ID: b69eaa119477
Revises: 5166955b27ea
Create Date: 2025-05-11 01:41:11.069607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b69eaa119477'
down_revision: Union[str, None] = '5166955b27ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'id')

    op.create_primary_key(
        'pk_refresh_tokens',
        'refresh_tokens',
        ['user_id', 'device_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('id', mysql.CHAR(length=36), nullable=False))
    op.create_index('id', 'refresh_tokens', ['id'], unique=True)

    op.drop_constraint('pk_refresh_tokens', 'refresh_tokens', type_='primary')

    op.create_primary_key(
        'pk_refresh_tokens',
        'refresh_tokens',
        ['id']
    )
    # ### end Alembic commands ###
