"""chat last message id fk

Revision ID: d1b50fefaa95
Revises: 79a8280af1c4
Create Date: 2025-05-29 23:00:26.225030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b50fefaa95'
down_revision: Union[str, None] = '79a8280af1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_chats_last_message_id', 'chats', 'messages', ['last_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chats_last_message_id', 'chats', type_='foreignkey')
    # ### end Alembic commands ###
