"""change image fields to keys fields

Revision ID: f6bb9c6e1b44
Revises: b69eaa119477
Create Date: 2025-05-22 12:49:58.931039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6bb9c6e1b44'
down_revision: Union[str, None] = 'b69eaa119477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_keys', sa.JSON(), nullable=False))
    op.drop_column('posts', 'image_exts')
    op.add_column('users', sa.Column('avatar_key', sa.String(length=41), nullable=True))
    op.drop_column('users', 'avatar_id')

    op.execute("UPDATE users SET avatar_type = NULL WHERE avatar_type = 'external'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', mysql.CHAR(length=36), nullable=True))
    op.drop_column('users', 'avatar_key')
    op.add_column('posts', sa.Column('image_exts', mysql.JSON(), nullable=False))
    op.drop_column('posts', 'image_keys')
    # ### end Alembic commands ###
