name: Deploy on Server

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test Docker Build
    runs-on: self-hosted

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            clean: false

        - name: Copy env file
          run: cp ~/envs/socially_app.env .env

        - name: Test Docker Compose build
          run: docker compose build

  deploy:
    name: Deploy to self-hosted server
    runs-on: self-hosted
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Copy env file
        run: cp ~/envs/socially_app.env .env

      - name: Build docker images
        run: docker compose build

      - name: Restart Services
        run: |
          docker compose down
          docker compose up -d --remove-orphans

      - name: Clean up unused images
        run: docker image prune -af
