name: Deploy on Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Docker Build
    runs-on: self-hosted

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            clean: false

        - name: Copy configuration files
          run: |
               cp ~/envs/socially_app.env .env
               cp ~/envs/socially_app_firebase_admin_cred.json config/firebase-admin-cred.json
        - name: Docker Compose build
          run: docker compose build

  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: Restart Services
        run: docker compose up -d --remove-orphans

      - name: Clean up unused images
        run: docker image prune -af
